package com.giannoules.proxstor.testing.generator;

import com.giannoules.proxstor.api.Sensor;
import com.giannoules.proxstor.api.SensorType;
import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import java.util.UUID;

public class SensorGenerator {
    
    static final String consonants = "BCDFGHJKLMNPQRSTVWXYZ";   
    static final String vowels = "AEIOU";
    static final String mixed = "-_!@#$%^&*()+";
    private final Random random;
    /*
     * uniqueness of sensor tied to sensorTYpe x typeIdentifier
     */
    private final Set<String> uniqueSensors;
    
    public SensorGenerator(Random random) {
        this.random = random;
        uniqueSensors = new HashSet<>();
    }
    
    public Sensor genSensor() {
        Sensor s = new Sensor();
        do {           
            SensorType st = SensorType.values()[random.nextInt(SensorType.values().length - 2) + 2];            
            s.setType(st);
            switch (s.getType()) {
                case BLE_UUID:                    
                case BT_UUID:
                    s.setTypeIdentifier(UUID.randomUUID().toString());
                    if (s.getType() == SensorType.BLE_UUID) {
                        s.setDescription("BLE UUID " + s.getTypeIdentifier());
                    } else {
                        s.setDescription("BT UUID " + s.getTypeIdentifier());
                    }
                    break;          
                case WIFI_BSSID:
                case WIFI_SSID:
                    int len = random.nextInt(20) + 5;
                    StringBuilder sb = new StringBuilder();
                    sb.append(consonants.charAt(random.nextInt(consonants.length())));
                    while (len > 0) {
                        switch (random.nextInt(5)) {
                            case 0:
                                sb.append(consonants.charAt(random.nextInt(consonants.length())));
                                break;
                            case 1:
                                sb.append(vowels.charAt(random.nextInt(vowels.length())));
                                break;
                            case 2:
                                sb.append(mixed.charAt(random.nextInt(mixed.length())));
                                break;                         
                        }
                        len--;
                    }
                    s.setTypeIdentifier(sb.toString());
                    if (s.getType() == SensorType.WIFI_BSSID) {
                        s.setDescription("WiFi BSSID " + s.getTypeIdentifier());
                    } else {
                        s.setDescription("WiFi SSID " + s.getTypeIdentifier());
                    }
                    break;                                                  
            }            
            /*
             * this a testing-specific misuse of the sensodId field needed to assist
             * in assigning a specific sensor "type" to locations
             * when the sensors are actually being inserted into ProxStor the
             * real UUID will be generated by the tool and sensorId field will be 
             * ignored and assigned on the webapi side of ProxStor
             */
            s.setSensorId(UUID.randomUUID().toString());
        } while (uniqueSensors.contains(s.getTypeIdentifier()));
        uniqueSensors.add(s.getTypeIdentifier());
        return s;
    }
    
}
